version: '3.9'
services:
  dgraph-standalone:
    container_name: dgraph-standalone
    image: dgraph/standalone:v20.03.0
    ports:
      - "8000:8000"
      - "8080:8080"
      - "9080:9080"
    volumes:
      - ~/dgraph:/dgraph  
  data-service:
    build: 
      context: ../..
      dockerfile: tools/dockerfiles/data-service.Dockerfile
    container_name: data-service
    image: unified-codes/data-service:latest
    ports:
      - "4000:4000"
    env_file:
      - .docker.env
    volumes:
      - ../../dist/apps/data-service:/usr/unified-codes/dist/apps/data-service

networks:
  default:
    external:
      name: net

volumes:
  logvolume01: {}
