export enum ECSVColumn {
    Product = 'product',
    ProductSynonym = 'product_synonym',
    Combination = 'combination',
    Route = 'route',
    DoseForm = 'dose_form',
    DoseQualification = 'dose_qualification',
    Strength = 'strength',
    UnitOfPresentation = 'unit_of_presentation',
    ImmediatePackaging = 'immediate_packaging',
    PackSize = 'pack_size',
    OuterPackaging = 'outer_packaging',
    Manufacturer = 'manufacturer',
    Brand = 'brand',
    UC1 = 'uc1',
    UC2 = 'uc2',
    UC3 = 'uc3',
    UC4 = 'uc4',
    UC5 = 'uc5',
    UC6 = 'uc6',
    UC7 = 'uc7',
    UC8 = 'uc8',
    UC9 = 'uc9',
    UC10 = 'uc10',
    UC11 = 'uc11',
    UC12 = 'uc12',
    RxNav = 'rxnav',
    WHOEMLProduct = 'who_eml_product',
    WHOEMLItem = 'who_eml_item',
    NZULM = 'nzulm',
    NZULMItem = 'nzulm_item',
    UNSPSC = 'unspsc'
  }

  export default ECSVColumn;