#!/bin/sh

## This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask universal_codes.service > /dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled universal_codes.service
then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable universal_codes.service > /dev/null || true
	deb-systemd-invoke restart universal_codes
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state universal_codes.service > /dev/null || true
	deb-systemd-invoke start universal_codes
fi