[tasks.watch_build]
script = "cargo watch -x build -s 'touch .trigger'"

[tasks.trigger_server_start]
# TODO dynamic port?????
script = "systemfd --no-pid -s http::4007 -- cargo watch --no-vcs-ignores -w .trigger -x run"

[tasks.watch]
workspace = false
run_task = { name = ["watch_build", "trigger_server_start"], parallel = true }
