export type DETAIL_ROUTE_PARAMETERS = { code: string };
export type ERROR_ROUTE_PARAMETERS = { code: string };
export type EXPLORER_ROUTE_PARAMETERS = {};

export type ROUTE_PARAMETERS = {
  DETAIL: DETAIL_ROUTE_PARAMETERS;
  ERROR: ERROR_ROUTE_PARAMETERS;
  EXPLORER: EXPLORER_ROUTE_PARAMETERS;
};

export default ROUTE_PARAMETERS;
