export const categories = {
  routes: [
    { label: 'Buccal', value: 'Buccal' },
    { label: 'Dental', value: 'Dental' },
    { label: 'Ear', value: 'Ear' },
    { label: 'Eye', value: 'Eye' },
    { label: 'Inhalation', value: 'Inhalation' },
    { label: 'Intratracheal', value: 'Intratracheal' },
    { label: 'Intrauterine', value: 'Intrauterine' },
    { label: 'Nasal', value: 'Nasal' },
    { label: 'Oral', value: 'Oral' },
    { label: 'Parenteral', value: 'Parenteral' },
    { label: 'Rectal', value: 'Rectal' },
    { label: 'Subdermal', value: 'Subdermal' },
    { label: 'Sublingual', value: 'Sublingual' },
    { label: 'Topical', value: 'Topical' },
    { label: 'Transdermal', value: 'Transdermal' },
    { label: 'Vaginal', value: 'Vaginal' },
  ],
  forms: [
    { label: 'Aerosol pressurised', value: 'Aerosol pressurised' },
    { label: 'Capsule', value: 'Capsule' },
    { label: 'Cream', value: 'Cream' },
    { label: 'Device', value: 'Device' },
    { label: 'Drop', value: 'Drop' },
    { label: 'Emulsion', value: 'Emulsion' },
    { label: 'Film', value: 'Film' },
    { label: 'Foam', value: 'Foam' },
    { label: 'Gas', value: 'Gas' },
    { label: 'Gel', value: 'Gel' },
    { label: 'Granules', value: 'Granules' },
    { label: 'Implant', value: 'Implant' },
    { label: 'Liquid', value: 'Liquid' },
    { label: 'Lotion', value: 'Lotion' },
    { label: 'Lozenge', value: 'Lozenge' },
    { label: 'Nebule', value: 'Nebule' },
    { label: 'Ointment', value: 'Ointment' },
    { label: 'Paint', value: 'Paint' },
    { label: 'Patch', value: 'Patch' },
    { label: 'Paste', value: 'Paste' },
    { label: 'Pessary', value: 'Pessary' },
    { label: 'Powder for reconstitution', value: 'Powder for reconstitution' },
    { label: 'Ring', value: 'Ring' },
    { label: 'Shampoo', value: 'Shampoo' },
    { label: 'Solution', value: 'Solution' },
    { label: 'Solution (Intramuscular)', value: 'Solution (Intramuscular)' },
    { label: 'Solution (Subcutaneous)', value: 'Solution (Subcutaneous)' },
    { label: 'Spray', value: 'Spray' },
    { label: 'Suppository', value: 'Suppository' },
    { label: 'Suspension', value: 'Suspension' },
    { label: 'Tablet', value: 'Tablet' },
    { label: 'Tablet (Chewable)', value: 'Tablet (Chewable)' },
    { label: 'Tablet (Crushable)', value: 'Tablet (Crushable)' },
    { label: 'Tablet (Dispersible)', value: 'Tablet (Dispersible)' },
    { label: 'Tablet (Enteric-coated)', value: 'Tablet (Enteric-coated)' },
    {
      label: 'Tablet (Extended-release)',
      value: 'Tablet (Extended-release)',
    },
    {
      label: 'Tablet (Immediate-release)',
      value: 'Tablet (Immediate-release)',
    },
    {
      label: 'Tablet (Prolonged-release)',
      value: 'Tablet (Prolonged-release)',
    },
    { label: 'Vapour', value: 'Vapour' },
    { label: 'Water', value: 'Water' },
  ],
};
