[package]
name = "graphql_v1_core"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]

repository = { path = "../../repository" }
service = { path = "../../service" }
util = { path = "../../util" }

actix-web = { version = "4.0.1", default-features = false, features = ["macros", "cookies"] }
async-graphql = { version = "3.0.35", features = ["dataloader", "chrono"] }
async-trait = "0.1.30"
chrono = { version = "0.4", features = ["serde"] }
reqwest = { version = "0.11", features = ["json"] }
serde = "1.0.126"
serde_json = "1.0.66"
tokio = { version = "1.29", features = ["macros" ] }
