type Property {
  type
  value
}

type Category {
  code
  name
  children
  properties
}

type Product {
  code
  name
  combines
  children
  properties
}

type Route {
  code
  name
  children
  properties
}

type DoseForm {
  code
  name
  children
  properties
}

type DoseFormQualifier {
  code
  name
  children
  properties
}

type DoseStrength {
  code
  name
  children
  properties
}

type DoseUnit {
  code
  name
  children
  properties
}

type PackImmediate {
  code
  name
  children
  properties
}

type PackSize {
  code
  name
  children
  properties
}

type PackOuter {
  code
  name
  children
  properties
}

code: string @index(exact, fulltext).
name: string @lang @index(exact, term, trigram) .
type: string @index(term) .
value: string .
combines: [uid] .
properties: [uid] .
children: [uid] @reverse . 