export const ENTITY_KEY = 'ENTITY';
export const ENTITIES_KEY = 'ENTITIES';
export const PENDING_CHANGE_KEY = 'PENDING_CHANGE';
export const PENDING_CHANGES_KEY = 'PENDING_CHANGES';
export const PROPERTY_CONFIG_ITEMS_KEY = 'PROPERTY_CONFIG_ITEMS';
export const BARCODES_KEY = 'BARCODES';
export const ENTITY_WITH_BARCODES_KEY = 'ENTITY_WITH_BARCODES';
