name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./api
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
      working-directory: ${{env.working-directory}}
    - name: Run tests
      run: npm test
      working-directory: ${{env.working-directory}}