name: CI
on: push
jobs:
  test-api:
    runs-on: ubuntu-latest
    env:
      api-directory: ./api
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
      working-directory: ${{env.api-directory}}
    - name: Run api tests
      run: npm run test-api 
      working-directory: ${{env.api-directory}}
  test-dgraph:
    runs-on: ubuntu-latest
    env:
      api-directory: ./api
      dgraph-directory: ./dgraph
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
      working-directory: ${{env.api-directory}}
    - name: Start docker
      run: bash ./docker.sh &
      working-directory: ${{env.dgraph-directory}}
    - name: Sleep
      run: sleep 20
    - name: Initialise data
      run: bash ./init.sh
      working-directory: ${{env.dgraph-directory}}
    - name: Run dgraph tests
      run: npm run test-dgraph
      working-directory: ${{env.api-directory}}