name: CI
on: push
jobs:
  check-types:
    runs-on: ubuntu-latest
    env:
      legacy-api-directory: ./unified-codes
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
      working-directory: ${{env.api-directory}}
    - name: Run legacy-api-directory type check
      run: npm run nx build legacy-api
      working-directory: ${{env.legacy-api-directory}}
  test-api:
    runs-on: ubuntu-latest
    env:
      api-directory: ./unified-codes
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
      working-directory: ${{env.legacy-api-directory}}
    - name: Run api tests
      run: npm run nx test api
      working-directory: ${{env.legacy-api-directory}}
  test-data-service:
    runs-on: ubuntu-latest
    env:
      legacy-api-directory: ./unified-codes
      database-directory: ./unified-codes/apps/data-service/src/app/database
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
      working-directory: ${{env.legacy-api-directory}}
    - name: Start docker
      run: sudo bash ./docker.sh &
      working-directory: ${{env.database-directory}}
    - name: Sleep
      run: sleep 20
    - name: Initialise data
      run: sudo bash ./init.sh
      working-directory: ${{env.database-directory}}
    - name: Run dgraph tests
      run: npm run test-dgraph
      working-directory: ${{env.legacy-api-directory}}