name: CI
on: push
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build frontend
        run: yarn build-frontend

      - name: Test frontend
        run: yarn test-frontend

      - name: Test backend
        run: yarn test-backend
