name: CI
on: push
jobs:
  check-types:
    runs-on: ubuntu-latest
    env:
      api-directory: ./api
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
      working-directory: ${{env.api-directory}}
    - name: Run api type check
      run: npm run check-types
      working-directory: ${{env.api-directory}}
  test-api:
    runs-on: ubuntu-latest
    env:
      api-directory: ./monorepo
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
      working-directory: ${{env.api-directory}}
    - name: Run api tests
      run: npm run nx test api
      working-directory: ${{env.api-directory}}
  test-data-service:
    runs-on: ubuntu-latest
    env:
      api-directory: ./monorepo
      database-directory: ./data-service/database
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
      working-directory: ${{env.api-directory}}
    - name: Start docker
      run: sudo bash ./docker.sh &
      working-directory: ${{env.database-directory}}
    - name: Sleep
      run: sleep 20
    - name: Initialise data
      run: sudo bash ./init.sh
      working-directory: ${{env.database-directory}}
    - name: Run dgraph tests
      run: npm run test-dgraph
      working-directory: ${{env.api-directory}}