name: CI
on: push
jobs:
  check-types-legacy-api:
    runs-on: ubuntu-latest
    env:
      workspace-directory: ./unified-codes
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
      working-directory: ${{env.workspace-directory}}
    - name: Run legacy-api type check
      run: npx nx build legacy-api
      working-directory: ${{env.workspace-directory}}
  test-legacy-api:
    runs-on: ubuntu-latest
    env:
      workspace-directory: ./unified-codes
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
      working-directory: ${{env.workspace-directory}}
    - name: Run legacy-api tests
      run: npx nx test legacy-api
      working-directory: ${{env.workspace-directory}}
  build-push-docker:
    runs-on: ubuntu-latest
    env:
      workspace-directory: ./unified-codes
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install modules
      run: npm install
      working-directory: ${{env.workspace-directory}}
    - name: Build legacy-api
      run: npx nx build legacy-api
      working-directory: ${{env.workspace-directory}}
    - name: Build data-service
      run: npx nx build data-service
      working-directory: ${{env.workspace-directory}}
      # Test only with temp access token! Credentials should be moved to GitHub secrets
    - name: Build and push unified-codes/dependencies
      uses: docker/build-push-action@v1
      with:
        username: katms
        password: f8b503fd-314f-4397-8c97-be8231647849
        path: ${{env.workspace-directory}}
        dockerfile: ${{env.workspace-directory}}/tools/dockerfiles/dependencies.Dockerfile
        repository: unifiedcodes/dependencies
        tags: latest
        push: true
    - name: Build and push legacy-api
      uses: docker/build-push-action@v1
      with:
        username: katms
        password: f8b503fd-314f-4397-8c97-be8231647849
        path: ${{env.workspace-directory}}
        dockerfile: ${{env.workspace-directory}}/tools/dockerfiles/legacy-api.Dockerfile
        repository: unifiedcodes/legacy-api
        tags: latest
        push: true
    - name: Build and push data-service
      uses: docker/build-push-action@v1
      with:
        username: katms
        password: f8b503fd-314f-4397-8c97-be8231647849
        path: ${{env.workspace-directory}}
        dockerfile: ${{env.workspace-directory}}/tools/dockerfiles/data-service.Dockerfile
        repository: unifiedcodes/data-service
        tags: latest
        push: true
